=== RUN  TestGolden
sha1[2](aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
) = 1f19f664d84d901a6cf9bd64507563c0ba369c1a want 76245dbf96f661bd221046197ab8b9f063f11badException: __fail__
Called from stdgo._internal.testing.$T_common_static_extension.failNow (stdgo/_internal/testing/Testing_t_common_static_extension.hx line 118)
Called from stdgo._internal.testing.$T_common_static_extension.fatalf (stdgo/_internal/testing/Testing_t_common_static_extension.hx line 69)
Called from stdgo._internal.testing.T_.~get_fatalf.0 (stdgo/_internal/testing/Testing_t_.hx line 47)
Called from stdgo._internal.crypto.sha1._Sha1_testgolden.$Sha1_testgolden_Fields_.testGolden (stdgo/_internal/crypto/sha1/Sha1_testgolden.hx line 41)
Called from stdgo._internal.testing.$M_static_extension.run (stdgo/_internal/testing/Testing_m_static_extension.hx line 34)
Called from _internal.crypto.sha1_dot_test._Sha1_dot_test.$Sha1_dot_test_Fields_.main (_internal/crypto/sha1_dot_test/Sha1_dot_test.hx line 4)

-- FAIL: TestGolden
