=== RUN  TestErrorf

-- PASS: TestErrorf

=== RUN  TestFmtInterface

-- PASS: TestFmtInterface

=== RUN  TestSprintf
Exception: _v.__copy__ is not a function
Called from module TypeError: _v.__copy__ is not a function
Called from stdgo__$internal_reflect_Value_$static_$extension.isValid (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 28458 column 28)
Called from stdgo__$internal_fmt_T_$pp_$static_$extension._printArg (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 25744 column 74)
Called from stdgo__$internal_fmt_T_$pp_$static_$extension._doPrintf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 23863 column 50)
Called from .stdgo__$internal_fmt_Fmt_$sprintf_sprintf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 18841 column 48)
Called from module at stdgo__$internal_testing_InternalTest._$internal_fmt_$test_Fmt_$test_$testsprintf_testSprintf [as f] (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:46468:14)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 85403 column 9)
Called from ._$internal_fmtdottest_Fmtdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75637 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105730:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105731:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestSprintf

=== RUN  TestComplexFormatting

-- PASS: TestComplexFormatting

=== RUN  TestReorder

-- PASS: TestReorder

=== RUN  TestCountMallocs
<invalid reflect.Value>
Exception: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 86190 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skip (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 86220 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:85630:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_fmt_$test_Fmt_$test_$testcountmallocs_testCountMallocs [as f] (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:44620:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 85403 column 9)
Called from ._$internal_fmtdottest_Fmtdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75637 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105730:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105731:3)

-- SKIP: TestCountMallocs

-- PASS: TestCountMallocs

=== RUN  TestFlagParser

-- PASS: TestFlagParser

=== RUN  TestStructPrinter
Sprintf(<invalid reflect.Value>, s) = %!q(MISSING), want %!q(MISSING)
Sprintf(<invalid reflect.Value>, &s) = %!q(MISSING), want %!q(MISSING)

-- FAIL: TestStructPrinter

=== RUN  TestSlicePrinter

-- PASS: TestSlicePrinter

=== RUN  TestMapPrinter

-- PASS: TestMapPrinter

=== RUN  TestEmptyMap

-- PASS: TestEmptyMap

=== RUN  TestBlank

-- PASS: TestBlank

=== RUN  TestBlankln

-- PASS: TestBlankln

=== RUN  TestFormatterPrintln

-- PASS: TestFormatterPrintln

=== RUN  TestWidthAndPrecision

-- PASS: TestWidthAndPrecision

=== RUN  TestPanics
-- SKIP: testPanics

-- PASS: TestPanics

=== RUN  TestBadVerbRecursion

-- PASS: TestBadVerbRecursion

=== RUN  TestIsSpace

-- PASS: TestIsSpace

=== RUN  TestNilDoesNotBecomeTyped
expected:
	<invalid reflect.Value>
got:
	%!q(MISSING)

-- FAIL: TestNilDoesNotBecomeTyped

=== RUN  TestFormatterFlags
Sprintf(<invalid reflect.Value>, %!T(MISSING)) = %!q(MISSING), want %!q(MISSING)

-- FAIL: TestFormatterFlags

=== RUN  TestParsenum

-- PASS: TestParsenum

=== RUN  TestAppendf
Exception: Cannot read properties of undefined (reading '_common')
Called from module TypeError: Cannot read properties of undefined (reading '_common')
Called from stdgo__$internal_internal_reflect__$Type_$static_$extension.string (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 19793 column 13)
Called from stdgo__$internal_internal_reflect__$Type_$asInterface.string (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 20211 column 70)
Called from stdgo__$internal_fmt_T_$pp_$static_$extension._doPrintf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 24417 column 73)
Called from .stdgo__$internal_fmt_Fmt_$fprintf_fprintf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 40621 column 48)
Called from .stdgo__$internal_fmt_Fmt_$printf_printf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75270 column 51)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatalf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 86234 column 42)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:85591:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_fmt_$test_Fmt_$test_$testappendf_testAppendf [as f] (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:44319:20)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 85403 column 9)
Called from ._$internal_fmtdottest_Fmtdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75637 column 59)

-- FAIL: TestAppendf

=== RUN  TestAppend
Exception: Cannot read properties of undefined (reading '_common')
Called from module TypeError: Cannot read properties of undefined (reading '_common')
Called from stdgo__$internal_internal_reflect__$Type_$static_$extension.string (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 19793 column 13)
Called from stdgo__$internal_internal_reflect__$Type_$asInterface.string (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 20211 column 70)
Called from stdgo__$internal_fmt_T_$pp_$static_$extension._doPrintf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 24417 column 73)
Called from .stdgo__$internal_fmt_Fmt_$fprintf_fprintf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 40621 column 48)
Called from .stdgo__$internal_fmt_Fmt_$printf_printf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75270 column 51)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatalf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 86234 column 42)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:85591:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_fmt_$test_Fmt_$test_$testappend_testAppend [as f] (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:44220:20)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 85403 column 9)
Called from ._$internal_fmtdottest_Fmtdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75637 column 59)

-- FAIL: TestAppend

=== RUN  TestAppendln
Exception: Cannot read properties of undefined (reading '_common')
Called from module TypeError: Cannot read properties of undefined (reading '_common')
Called from stdgo__$internal_internal_reflect__$Type_$static_$extension.string (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 19793 column 13)
Called from stdgo__$internal_internal_reflect__$Type_$asInterface.string (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 20211 column 70)
Called from stdgo__$internal_fmt_T_$pp_$static_$extension._doPrintf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 24417 column 73)
Called from .stdgo__$internal_fmt_Fmt_$fprintf_fprintf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 40621 column 48)
Called from .stdgo__$internal_fmt_Fmt_$printf_printf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75270 column 51)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatalf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 86234 column 42)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:85591:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_fmt_$test_Fmt_$test_$testappendln_testAppendln [as f] (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:44418:20)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 85403 column 9)
Called from ._$internal_fmtdottest_Fmtdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75637 column 59)

-- FAIL: TestAppendln

=== RUN  TestScan
-- SKIP: testScan
 skip targets: js

-- PASS: TestScan

=== RUN  TestScanln
-- SKIP: testScanln
 skip targets: js

-- PASS: TestScanln

=== RUN  TestScanf
Exception: array out of bounds, index: 0 length: 0
Called from stdgo__$internal_fmt_T_$ss_$static_$extension._doScanf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 49684 column 25)
Called from .stdgo__$internal_fmt_Fmt_$fscanf_fscanf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 49018 column 62)
Called from .stdgo__$internal_fmt_Fmt_$sscanf_sscanf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 48954 column 49)
Called from module at stdgo__$internal_testing_InternalTest._$internal_fmt_$test_Fmt_$test_$testscanf_testScanf [as f] (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:45991:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 85403 column 9)
Called from ._$internal_fmtdottest_Fmtdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75637 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105730:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105731:3)

-- FAIL: TestScanf

=== RUN  TestScanOverflow
expected overflow scanning <invalid reflect.Value>
expected overflow scanning <invalid reflect.Value>
expected overflow scanning <invalid reflect.Value>
expected overflow scanning <invalid reflect.Value>
expected overflow scanning <invalid reflect.Value>
expected overflow scanning <invalid reflect.Value>
expected overflow scanning <invalid reflect.Value>
expected overflow scanning <invalid reflect.Value>
expected overflow scanning <invalid reflect.Value>
expected overflow scanning <invalid reflect.Value>
expected overflow scanning <invalid reflect.Value>

-- FAIL: TestScanOverflow

=== RUN  TestNaN

-- PASS: TestNaN

=== RUN  TestInf

-- PASS: TestInf

=== RUN  TestScanfMulti
-- SKIP: testScanfMulti
 skip targets: js

-- PASS: TestScanfMulti

=== RUN  TestScanMultiple
Exception: {
	__self__ : 0x633, 
	__type__ : {
		gt : refType({
				get : <function>
			})
	}
}
Called from module gt : refType({
Called from module get : <function>
Called from module })
Called from module }
Called from module }
Called from .new haxe_ValueException (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 30035 column 17)
Called from haxe_Exception.thrown (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 29965 column 11)
Called from stdgo__$internal_fmt_T_$ss_$static_$extension._doScan (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 49857 column 25)
Called from .stdgo__$internal_fmt_Fmt_$fscan_fscan (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 67263 column 62)
Called from .stdgo__$internal_fmt_Fmt_$sscan_sscan (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 67199 column 47)
Called from module at stdgo__$internal_testing_InternalTest._$internal_fmt_$test_Fmt_$test_$testscanmultiple_testScanMultiple [as f] (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:46261:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 85403 column 9)
Called from ._$internal_fmtdottest_Fmtdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75637 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105730:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105731:3)

-- FAIL: TestScanMultiple

=== RUN  TestScanEmpty
Exception: {
	__self__ : 0x633, 
	__type__ : {
		gt : refType({
				get : <function>
			})
	}
}
Called from module gt : refType({
Called from module get : <function>
Called from module })
Called from module }
Called from module }
Called from .new haxe_ValueException (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 30035 column 17)
Called from haxe_Exception.thrown (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 29965 column 11)
Called from stdgo__$internal_fmt_T_$ss_$static_$extension._doScan (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 49857 column 25)
Called from .stdgo__$internal_fmt_Fmt_$fscan_fscan (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 67263 column 62)
Called from .stdgo__$internal_fmt_Fmt_$sscan_sscan (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 67199 column 47)
Called from module at stdgo__$internal_testing_InternalTest._$internal_fmt_$test_Fmt_$test_$testscanempty_testScanEmpty [as f] (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:45939:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 85403 column 9)
Called from ._$internal_fmtdottest_Fmtdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75637 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105730:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105731:3)

-- FAIL: TestScanEmpty

=== RUN  TestScanNotPointer
Exception: _v.set is not a function
Called from stdgo__$internal_fmt_T_$ss_$static_$extension._doScan (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 49857 column 25)
Called from .stdgo__$internal_fmt_Fmt_$fscan_fscan (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 67263 column 62)
Called from module at stdgo__$internal_testing_InternalTest._$internal_fmt_$test_Fmt_$test_$testscannotpointer_testScanNotPointer [as f] (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:46326:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 85403 column 9)
Called from ._$internal_fmtdottest_Fmtdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75637 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105730:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105731:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestScanNotPointer

=== RUN  TestScanlnNoNewline
<invalid reflect.Value>

-- FAIL: TestScanlnNoNewline

=== RUN  TestScanlnWithMiddleNewline
<invalid reflect.Value>

-- FAIL: TestScanlnWithMiddleNewline

=== RUN  TestEOF
Exception: {
	__self__ : 0x633, 
	__type__ : {
		gt : refType({
				get : <function>
			})
	}
}
Called from module gt : refType({
Called from module get : <function>
Called from module })
Called from module }
Called from module }
Called from .new haxe_ValueException (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 30035 column 17)
Called from haxe_Exception.thrown (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 29965 column 11)
Called from stdgo__$internal_fmt_T_$ss_$static_$extension._doScan (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 49857 column 25)
Called from .stdgo__$internal_fmt_Fmt_$fscanln_fscanln (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 72487 column 62)
Called from module at stdgo__$internal_testing_InternalTest._$internal_fmt_$test_Fmt_$test_$testeof_testEOF [as f] (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:44719:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 85403 column 9)
Called from ._$internal_fmtdottest_Fmtdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75637 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105730:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105731:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestEOF

=== RUN  TestEOFAtEndOfInput
Exception: {
	__self__ : 0x633, 
	__type__ : {
		gt : refType({
				get : <function>
			})
	}
}
Called from module gt : refType({
Called from module get : <function>
Called from module })
Called from module }
Called from module }
Called from .new haxe_ValueException (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 30035 column 17)
Called from haxe_Exception.thrown (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 29965 column 11)
Called from stdgo__$internal_fmt_T_$ss_$static_$extension._doScanf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 49684 column 25)
Called from .stdgo__$internal_fmt_Fmt_$fscanf_fscanf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 49018 column 62)
Called from .stdgo__$internal_fmt_Fmt_$sscanf_sscanf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 48954 column 49)
Called from module at stdgo__$internal_testing_InternalTest._$internal_fmt_$test_Fmt_$test_$testeofatendofinput_testEOFAtEndOfInput [as f] (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:44798:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 85403 column 9)
Called from ._$internal_fmtdottest_Fmtdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75637 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105730:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105731:3)

-- FAIL: TestEOFAtEndOfInput

=== RUN  TestEOFAllTypes
Exception: {
	__self__ : 0x633, 
	__type__ : {
		gt : refType({
				get : <function>
			})
	}
}
Called from module gt : refType({
Called from module get : <function>
Called from module })
Called from module }
Called from module }
Called from .new haxe_ValueException (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 30035 column 17)
Called from haxe_Exception.thrown (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 29965 column 11)
Called from stdgo__$internal_fmt_T_$ss_$static_$extension._doScanf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 49684 column 25)
Called from .stdgo__$internal_fmt_Fmt_$fscanf_fscanf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 49018 column 62)
Called from .stdgo__$internal_fmt_Fmt_$sscanf_sscanf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 48954 column 49)
Called from module at stdgo__$internal_testing_InternalTest._$internal_fmt_$test_Fmt_$test_$testeofalltypes_testEOFAllTypes [as f] (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:44767:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 85403 column 9)
Called from ._$internal_fmtdottest_Fmtdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75637 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105730:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105731:3)

-- FAIL: TestEOFAllTypes

=== RUN  TestUnreadRuneWithBufio

-- PASS: TestUnreadRuneWithBufio

=== RUN  TestMultiLine
<invalid reflect.Value>

-- FAIL: TestMultiLine

=== RUN  TestLineByLineFscanf

-- PASS: TestLineByLineFscanf

=== RUN  TestScanStateCount

-- PASS: TestScanStateCount

=== RUN  TestScanInts
bad scan: expected <invalid reflect.Value> got %!d(MISSING)Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 86346 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatalf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 86235 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:85591:58
Called from ._$internal_fmt_$test_Fmt_$test_$_$testscanints__testScanInts (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 41542 column 4)
Called from module at stdgo__$internal_testing_InternalTest._$internal_fmt_$test_Fmt_$test_$testscanints_testScanInts [as f] (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:46089:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 85403 column 9)
Called from ._$internal_fmtdottest_Fmtdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75637 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105730:1

-- FAIL: TestScanInts

=== RUN  TestHexBytes
<invalid reflect.Value>: bad length %!d(MISSING)
<invalid reflect.Value>: bad length %!d(MISSING)
<invalid reflect.Value>: bad length %!d(MISSING)
<invalid reflect.Value>: bad length %!d(MISSING)
<invalid reflect.Value>: bad length %!d(MISSING)
<invalid reflect.Value>: bad length %!d(MISSING)
odd count: got count, err = <invalid reflect.Value>, %!v(MISSING); expected 0, error

-- FAIL: TestHexBytes

=== RUN  TestScanNewlinesAreSpaces

-- PASS: TestScanNewlinesAreSpaces

=== RUN  TestScanlnNewlinesTerminate
<invalid reflect.Value>: expected error; got none
<invalid reflect.Value>: expected error; got none

-- FAIL: TestScanlnNewlinesTerminate

=== RUN  TestScanfNewlineMatchFormat
<invalid reflect.Value>: expected error; got none
<invalid reflect.Value>: expected error; got none
<invalid reflect.Value>: expected error; got none
<invalid reflect.Value>: expected error; got none
<invalid reflect.Value>: expected error; got none
<invalid reflect.Value>: expected error; got none
<invalid reflect.Value>: expected error; got none
<invalid reflect.Value>: expected error; got none
<invalid reflect.Value>: expected error; got none

-- FAIL: TestScanfNewlineMatchFormat

=== RUN  TestHexByte
expected 0123 got <invalid reflect.Value>Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 86346 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatalf (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 86235 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:85591:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_fmt_$test_Fmt_$test_$testhexbyte_testHexByte [as f] (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:45505:3)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 85403 column 9)
Called from ._$internal_fmtdottest_Fmtdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js line 75637 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105730:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_fmt.js:105731:3)

-- FAIL: TestHexByte

=== RUN  TestFormatString

-- PASS: TestFormatString

=== RUN  TestStringer

-- PASS: TestStringer

./stdgo/_internal/testing/Testing_m_static_extension.hx:60: exitCode: 1
./stdgo/_internal/testing/Testing_m_static_extension.hx:61: exitCodeReason: 
-- FAIL: TestHexByte
