=== RUN  TestFormatFileInfo

-- PASS: TestFormatFileInfo

=== RUN  TestFormatDirEntry

-- PASS: TestFormatDirEntry

=== RUN  TestValidPath

-- PASS: TestValidPath

=== RUN  TestGlob
Exception: ENOENT: no such file or directory, scandir ''
Called from .stdgo__$internal_io_fs_Fs_$readdir_readDir (/home/runner/work/go2hx/go2hx/golibs/std_fs.js line 23208 column 25)
Called from .stdgo__$internal_io_fs_Fs_$_$glob__glob (/home/runner/work/go2hx/go2hx/golibs/std_fs.js line 22950 column 16)
Called from .stdgo__$internal_io_fs_Fs_$_$globwithlimit__globWithLimit (/home/runner/work/go2hx/go2hx/golibs/std_fs.js line 19856 column 17)
Called from .stdgo__$internal_io_fs_Fs_$glob_glob (/home/runner/work/go2hx/go2hx/golibs/std_fs.js line 19742 column 16)
Called from module at stdgo__$internal_testing_InternalTest._$internal_io_fs_$test_Fs_$test_$testglob_testGlob [as f] (/home/runner/work/go2hx/go2hx/golibs/std_fs.js:19706:17)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fs.js line 49081 column 9)
Called from ._$internal_io_fs_$dot_$test_Fs_$dot_$test_main (/home/runner/work/go2hx/go2hx/golibs/std_fs.js line 41193 column 59)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_fs.js:55486:1

-- FAIL: TestGlob

=== RUN  TestGlobError

-- PASS: TestGlobError

=== RUN  TestCVE202230630
-- SKIP: testCVE202230630

-- PASS: TestCVE202230630

=== RUN  TestGlobMethod

-- PASS: TestGlobMethod

=== RUN  TestReadDir

-- PASS: TestReadDir

=== RUN  TestFileInfoToDirEntry

-- PASS: TestFileInfoToDirEntry

=== RUN  TestReadFile

-- PASS: TestReadFile

=== RUN  TestStat

-- PASS: TestStat

=== RUN  TestSub

-- PASS: TestSub

=== RUN  TestWalkDir

-- PASS: TestWalkDir

=== RUN  TestIssue51617
got directories <invalid reflect.Value>, want %!v(MISSING)
chmod: invalid mode: ‘448’
Try 'chmod --help' for more information.
node:fs:1581
  const result = binding.readdir(
                         ^

Error: EACCES: permission denied, scandir '53bc1qfy6z/a/bad'
    at Object.readdirSync (node:fs:1581:26)
    at deleteRecursively (/home/runner/work/go2hx/go2hx/golibs/std_fs.js:45407:30)
    at deleteRecursively (/home/runner/work/go2hx/go2hx/golibs/std_fs.js:45413:7)
    at deleteRecursively (/home/runner/work/go2hx/go2hx/golibs/std_fs.js:45413:7)
    at stdgo__$internal_os_Os_$removeall_removeAll (/home/runner/work/go2hx/go2hx/golibs/std_fs.js:45453:2)
    at /home/runner/work/go2hx/go2hx/golibs/std_fs.js:49658:4
    at stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_fs.js:49095:4)
    at _$internal_io_fs_$dot_$test_Fs_$dot_$test_main (/home/runner/work/go2hx/go2hx/golibs/std_fs.js:41193:59)
    at /home/runner/work/go2hx/go2hx/golibs/std_fs.js:55486:1
    at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_fs.js:55487:3) {
  errno: -13,
  code: 'EACCES',
  syscall: 'scandir',
  path: '53bc1qfy6z/a/bad'
}

Node.js v23.8.0
