package stdgo._internal.internal.oserror;
@:keep var __init_go2hx__ = {
        try {
            var __tmp__0 = stdgo._internal.internal.oserror.Oserror_errinvalid.errInvalid, __tmp__1 = stdgo._internal.internal.oserror.Oserror_errpermission.errPermission, __tmp__2 = stdgo._internal.internal.oserror.Oserror_errexist.errExist, __tmp__3 = stdgo._internal.internal.oserror.Oserror_errnotexist.errNotExist, __tmp__4 = stdgo._internal.internal.oserror.Oserror_errclosed.errClosed;
        } catch(__exception__) if (__exception__.message != "__return__") throw __exception__;
        true;
    };
