package stdgo._internal.io.fs;
function _errClosed():stdgo.Error {
        return stdgo._internal.internal.oserror.Oserror_errclosed.errClosed;
    }
