package stdgo._internal.io.fs;
function _errNotExist():stdgo.Error {
        return stdgo._internal.internal.oserror.Oserror_errnotexist.errNotExist;
    }
