=== RUN  TestExpand
Exception: :os.expand is not yet implemented
Called from .stdgo__$internal_os_Os_$expand_expand (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59397 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testexpand_testExpand [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48956:14)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestExpand

=== RUN  TestConsistentEnviron

-- PASS: TestConsistentEnviron

=== RUN  TestUnsetenv
Exception: :os.setenv is not yet implemented
Called from .stdgo__$internal_os_Os_$setenv_setenv (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59459 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testunsetenv_testUnsetenv [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:58847:13)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestUnsetenv

=== RUN  TestClearenv
Exception: :os.setenv is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testclearenv_testClearenv [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:47659:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestClearenv

=== RUN  TestLookupEnv
Exception: :os.lookupEnv is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testlookupenv_testLookupEnv [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50883:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestLookupEnv

=== RUN  TestEnvironConsistency

-- PASS: TestEnvironConsistency

=== RUN  TestErrIsExist
<invalid reflect.Value>
Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testerrisexist_testErrIsExist [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48633:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestErrIsExist

=== RUN  TestErrIsNotExist
<invalid reflect.Value>
Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105867 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatal (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105811 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105341:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testerrisnotexist_testErrIsNotExist [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48647:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1

-- FAIL: TestErrIsNotExist

=== RUN  TestIsExist
Exception: :os.isExist is not yet implemented
Called from .stdgo__$internal_os_Os_$isexist_isExist (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 60025 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testisexist_testIsExist [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50057:13)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestIsExist

=== RUN  TestIsPermission
Exception: :os.isPermission is not yet implemented
Called from .stdgo__$internal_os_Os_$ispermission_isPermission (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 60034 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testispermission_testIsPermission [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50081:14)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestIsPermission

=== RUN  TestErrPathNUL
<invalid reflect.Value>
Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testerrpathnul_testErrPathNUL [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48789:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestErrPathNUL

=== RUN  TestPathErrorUnwrap

-- PASS: TestPathErrorUnwrap

=== RUN  TestErrorIsMethods
Exception: :os.isPermission is not yet implemented
Called from .stdgo__$internal_os_Os_$ispermission_isPermission (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 60034 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testerrorismethods_testErrorIsMethods [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48660:5)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestErrorIsMethods

=== RUN  TestExecutable
Exception: :os.executable is not yet implemented
Called from .stdgo__$internal_os_Os_$executable_executable (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 42964 column 23)
Called from .stdgo__$internal_internal_testenv_Testenv_$_$tryexec__tryExec (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 60223 column 16)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:60038:73
Called from stdgo__$internal_sync_Once_$static_$extension.do_ (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 60192 column 2)
Called from .stdgo__$internal_internal_testenv_Testenv_$musthaveexec_mustHaveExec (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 60037 column 48)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testexecutable_testExecutable [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48795:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)

-- FAIL: TestExecutable

=== RUN  TestExecutableDeleted
skipping test: 'go build' unavailable: <invalid reflect.Value>Exception: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105751 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105766 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105404:58
Called from stdgo__$internal_testing_T_$_$asInterface.skipf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 60368 column 54)
Called from .stdgo__$internal_internal_testenv_Testenv_$musthavegobuild_mustHaveGoBuild (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 63456 column 6)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testexecutabledeleted_testExecutableDeleted [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48882:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)

-- SKIP: TestExecutableDeleted

-- PASS: TestExecutableDeleted

=== RUN  TestStat
<invalid reflect.Value>
<invalid reflect.Value>
Exception: __fail__
Called from ._$internal_os_$test_Os_$test_$_$size__size (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 44365 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$teststat_testStat [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:57667:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestStat

=== RUN  TestStatError
Exception: Cannot read properties of undefined (reading '_common')
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$teststaterror_testStatError [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:57988:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestStatError

=== RUN  TestStatSymlinkLoop
Exception: :os.symlink is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$teststatsymlinkloop_testStatSymlinkLoop [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:58371:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestStatSymlinkLoop

=== RUN  TestFstat
<invalid reflect.Value>
Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testfstat_testFstat [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49495:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestFstat

=== RUN  TestLstat
<invalid reflect.Value>
<invalid reflect.Value>
Exception: __fail__
Called from ._$internal_os_$test_Os_$test_$_$size__size (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 44365 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testlstat_testLstat [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50909:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestLstat

=== RUN  TestRead0
<invalid reflect.Value>
Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testread0_testRead0 [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:53359:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestRead0

=== RUN  TestReadClosed
<invalid reflect.Value>
Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105867 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatal (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105811 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105341:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreadclosed_testReadClosed [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:53786:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1

-- FAIL: TestReadClosed

=== RUN  TestFileReaddirnames
- SUBRUN  .
open <invalid reflect.Value> failed: %!v(MISSING)Exception: __fail__
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:45509:26
Called from stdgo__$internal_testing_T_$_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59482 column 2)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testfilereaddirnames_testFileReaddirnames [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49371:50)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)

-- FAIL: TestFileReaddirnames

=== RUN  TestFileReaddir
- SUBRUN  .
open <invalid reflect.Value> failed: %!v(MISSING)Exception: __fail__
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:45198:26
Called from stdgo__$internal_testing_T_$_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59482 column 2)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testfilereaddir_testFileReaddir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49321:50)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)

-- FAIL: TestFileReaddir

=== RUN  TestFileReadDir
- SUBRUN  .
open <invalid reflect.Value> failed: %!v(MISSING)Exception: __fail__
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:45388:26
Called from stdgo__$internal_testing_T_$_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59482 column 2)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testfilereaddir_testFileReadDir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49346:50)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)

-- FAIL: TestFileReadDir

=== RUN  TestReaddirnamesOneAtATime
open <invalid reflect.Value> failed: %!v(MISSING)Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreaddirnamesoneatatime_testReaddirnamesOneAtATime [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:54075:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestReaddirnamesOneAtATime

=== RUN  TestReaddirNValues
<invalid reflect.Value>
Exception: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105751 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skip (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105781 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105389:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreaddirnvalues_testReaddirNValues [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:54082:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1

-- SKIP: TestReaddirNValues

-- PASS: TestReaddirNValues

=== RUN  TestReaddirStatFailures
Exception: Cannot read properties of null (reading 'previous')
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreaddirstatfailures_testReaddirStatFailures [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:54753:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestReaddirStatFailures

=== RUN  TestReaddirOfFile
Exception: File:os.readdirnames is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreaddiroffile_testReaddirOfFile [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:54305:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestReaddirOfFile

=== RUN  TestHardLink
skipping test: hardlinks are not supported on <invalid reflect.Value>/%!s(MISSING)Exception: __skip__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testhardlink_testHardLink [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50000:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- SKIP: TestHardLink

-- PASS: TestHardLink

=== RUN  TestSymlink
Exception: :os.symlink is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testsymlink_testSymlink [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:58570:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestSymlink

=== RUN  TestLongSymlink
Exception: :os.symlink is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testlongsymlink_testLongSymlink [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50786:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestLongSymlink

=== RUN  TestRename
Exception: :os.rename is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testrename_testRename [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:56213:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestRename

=== RUN  TestRenameOverwriteDest
write file <invalid reflect.Value> failed: %!v(MISSING)Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testrenameoverwritedest_testRenameOverwriteDest [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:56758:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestRenameOverwriteDest

=== RUN  TestRenameFailed
Exception: :os.rename is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testrenamefailed_testRenameFailed [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:56566:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestRenameFailed

=== RUN  TestRenameNotExisting
Exception: :os.rename is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testrenamenotexisting_testRenameNotExisting [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:56649:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestRenameNotExisting

=== RUN  TestRenameToDirFailed
Exception: :os.rename is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testrenametodirfailed_testRenameToDirFailed [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:56965:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestRenameToDirFailed

=== RUN  TestRenameCaseDifference
- SUBRUN  dir
Exception: :os.isNotExist is not yet implemented
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:56358:28
Called from stdgo__$internal_testing_T_$_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59482 column 2)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testrenamecasedifference_testRenameCaseDifference [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:56248:51)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)

-- FAIL: TestRenameCaseDifference

=== RUN  TestStartProcess
Exception: :os.exec.lookPath is not yet implemented
Called from .stdgo__$internal_os_exec_Exec_$lookpath_lookPath (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 63515 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$teststartprocess_testStartProcess [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:57627:17)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestStartProcess

=== RUN  TestChmod
Stat <invalid reflect.Value>: mode %!o(MISSING) want %!o(MISSING)
Exception: File:os.chmod is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testchmod_testChmod [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:46678:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestChmod

=== RUN  TestFTruncate
Exception: File:os.stat is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testftruncate_testFTruncate [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49594:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestFTruncate

=== RUN  TestTruncate
Exception: File:os.stat is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testtruncate_testTruncate [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:58718:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestTruncate

=== RUN  TestTruncateNonexistentFile
./stdgo/_internal/os/Os_truncate.hx:3: os.truncate not implemented
got error: <invalid reflect.Value>
want an ErrNotExist PathError with path %!q(MISSING)
got error: <invalid reflect.Value>
want an ErrNotExist PathError with path %!q(MISSING)

-- FAIL: TestTruncateNonexistentFile

=== RUN  TestChtimes
Exception: stdgo__$internal_os_Os_$atime_atime is not a function
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testchtimes_testChtimes [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:46966:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestChtimes

=== RUN  TestChtimesWithZeroTimes
Exception: stdgo__$internal_os_Os_$atime_atime is not a function
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testchtimeswithzerotimes_testChtimesWithZeroTimes [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:47551:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestChtimesWithZeroTimes

=== RUN  TestChtimesDir
Exception: stdgo__$internal_os_Os_$atime_atime is not a function
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testchtimesdir_testChtimesDir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:47045:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestChtimesDir

=== RUN  TestChtimesToUnixZero
Exception: :os.chtimes is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testchtimestounixzero_testChtimesToUnixZero [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:47170:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestChtimesToUnixZero

=== RUN  TestFileChdir
Open .: <invalid reflect.Value>Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testfilechdir_testFileChdir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49109:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestFileChdir

=== RUN  TestChdirAndGetwd
Open .: <invalid reflect.Value>Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105867 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatalf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105796 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105350:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testchdirandgetwd_testChdirAndGetwd [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:46476:20)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1

-- FAIL: TestChdirAndGetwd

=== RUN  TestProgWideChdir

-- PASS: TestProgWideChdir

=== RUN  TestSeek
#<invalid reflect.Value>: Seek(%!v(MISSING), %!v(MISSING)) = %!v(MISSING), %!v(MISSING) want %!v(MISSING), nil
#<invalid reflect.Value>: Seek(%!v(MISSING), %!v(MISSING)) = %!v(MISSING), %!v(MISSING) want %!v(MISSING), nil
#<invalid reflect.Value>: Seek(%!v(MISSING), %!v(MISSING)) = %!v(MISSING), %!v(MISSING) want %!v(MISSING), nil
#<invalid reflect.Value>: Seek(%!v(MISSING), %!v(MISSING)) = %!v(MISSING), %!v(MISSING) want %!v(MISSING), nil
#<invalid reflect.Value>: Seek(%!v(MISSING), %!v(MISSING)) = %!v(MISSING), %!v(MISSING) want %!v(MISSING), nil
#<invalid reflect.Value>: Seek(%!v(MISSING), %!v(MISSING)) = %!v(MISSING), %!v(MISSING) want %!v(MISSING), nil
#<invalid reflect.Value>: Seek(%!v(MISSING), %!v(MISSING)) = %!v(MISSING), %!v(MISSING) want %!v(MISSING), nil

-- FAIL: TestSeek

=== RUN  TestSeekError
skipping test on <invalid reflect.Value>Exception: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105751 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105766 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105404:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testseekerror_testSeekError [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:57331:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1

-- SKIP: TestSeekError

-- PASS: TestSeekError

=== RUN  TestOpenError
Exception: EACCES: permission denied, open '/etc/no-such-file'
Called from Object.openSync (node:fs line 563 column 18)
Called from Object.writeFileSync (node:fs line 2441 column 35)
Called from .stdgo__$internal_os_Os_$openfile_openFile (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59691 column 14)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testopenerror_testOpenError [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:52050:17)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestOpenError

=== RUN  TestOpenNoName
Exception: ENOENT: no such file or directory, open ''
Called from Object.openSync (node:fs line 563 column 18)
Called from Object.writeFileSync (node:fs line 2441 column 35)
Called from .stdgo__$internal_os_Os_$openfile_openFile (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59691 column 14)
Called from .stdgo__$internal_os_Os_$open_open (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 60028 column 9)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testopennoname_testOpenNoName [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:52253:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)

-- FAIL: TestOpenNoName

=== RUN  TestHostname
Exception: :os.hostname is not yet implemented
Called from .stdgo__$internal_os_Os_$hostname_hostname (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66184 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testhostname_testHostname [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50007:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestHostname

=== RUN  TestReadAt

-- PASS: TestReadAt

=== RUN  TestReadAtOffset

-- PASS: TestReadAtOffset

=== RUN  TestReadAtNegativeOffset
ReadAt(-10) = <invalid reflect.Value>, %!v(MISSING); want 0, ...%!q(MISSING)...

-- FAIL: TestReadAtNegativeOffset

=== RUN  TestWriteAt

-- PASS: TestWriteAt

=== RUN  TestWriteAtNegativeOffset
WriteAt(-10) = <invalid reflect.Value>, %!v(MISSING); want 0, ...%!q(MISSING)...

-- FAIL: TestWriteAtNegativeOffset

=== RUN  TestWriteAtInAppendMode

-- PASS: TestWriteAtInAppendMode

=== RUN  TestAppend
writeFile: have <invalid reflect.Value> want %!q(MISSING)Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testappend_testAppend [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:46466:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestAppend

=== RUN  TestStatDirWithTrailingSlash

-- PASS: TestStatDirWithTrailingSlash

=== RUN  TestNilProcessStateString
Exception: ProcessState:os.string is not yet implemented
Called from stdgo__$internal_os_ProcessState_$static_$extension.string (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66448 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testnilprocessstatestring_testNilProcessStateString [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:52036:64)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestNilProcessStateString

=== RUN  TestSameFile
Exception: :os.sameFile is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testsamefile_testSameFile [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:57077:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestSameFile

=== RUN  TestDevNullFile
Exception: File:os.stat is not yet implemented
Called from ._$internal_os_$test_Os_$test_$_$testdevnullfile__testDevNullFile (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 44597 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdevnullfile_testDevNullFile [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48126:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestDevNullFile

=== RUN  TestLargeWriteToConsole
<invalid reflect.Value>
Exception: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105751 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skip (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105781 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105389:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testlargewritetoconsole_testLargeWriteToConsole [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50122:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1

-- SKIP: TestLargeWriteToConsole

-- PASS: TestLargeWriteToConsole

=== RUN  TestStatDirModeExec
Stat <invalid reflect.Value>: mode %!o(MISSING) want %!o(MISSING)

-- FAIL: TestStatDirModeExec

=== RUN  TestStatStdin
Exception: File:os.stat is not yet implemented
Called from stdgo__$internal_os_File_$static_$extension.stat (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 42669 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$teststatstdin_testStatStdin [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:58148:60)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestStatStdin

=== RUN  TestStatRelativeSymlink
Exception: File:os.stat is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$teststatrelativesymlink_testStatRelativeSymlink [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:58106:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestStatRelativeSymlink

=== RUN  TestReadAtEOF
ReadAt failed: <invalid reflect.Value>Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreadateof_testReadAtEOF [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:53556:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestReadAtEOF

=== RUN  TestLongPath
- SUBRUN  length=247
Exception: :os.mkdirAll is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testlongpath_testLongPath [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50687:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestLongPath

=== RUN  TestKillStartProcess
Exception: :context.background is not yet implemented
Called from ._$internal_os_$test_Os_$test_$_$testkillprocess__testKillProcess (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 45076 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testkillstartprocess_testKillStartProcess [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50113:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestKillStartProcess

=== RUN  TestGetppid
Exception: :context.background is not yet implemented
Called from .stdgo__$internal_context_Context_$background_background (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 63437 column 23)
Called from .stdgo__$internal_internal_testenv_Testenv_$command_command (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 60565 column 97)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testgetppid_testGetppid [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49622:14)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)

-- FAIL: TestGetppid

=== RUN  TestKillFindProcess
Exception: :context.background is not yet implemented
Called from ._$internal_os_$test_Os_$test_$_$testkillprocess__testKillProcess (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 45076 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testkillfindprocess_testKillFindProcess [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50092:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestKillFindProcess

=== RUN  TestNilFileMethods
Exception: File:os.chdir is not yet implemented
Called from stdgo__$internal_os_File_$static_$extension.chdir (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 42693 column 23)
Called from Object._f (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 110903 column 54)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testnilfilemethods_testNilFileMethods [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:52028:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)

-- FAIL: TestNilFileMethods

=== RUN  TestRemoveAllRace

-- PASS: TestRemoveAllRace

=== RUN  TestPipeThreads
<invalid reflect.Value>
Exception: __skip__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testpipethreads_testPipeThreads [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:52931:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- SKIP: TestPipeThreads

-- PASS: TestPipeThreads

=== RUN  TestDoubleCloseError
- SUBRUN  file
<invalid reflect.Value>
Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105867 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatal (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105811 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105341:58
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:44682:20
Called from stdgo__$internal_testing_T_$_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59482 column 2)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdoublecloseerror_testDoubleCloseError [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48492:50)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)

-- FAIL: TestDoubleCloseError

=== RUN  TestUserHomeDir
Exception: :os.userHomeDir is not yet implemented
Called from .stdgo__$internal_os_Os_$userhomedir_userHomeDir (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66590 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testuserhomedir_testUserHomeDir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:58864:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestUserHomeDir

=== RUN  TestDirSeek
<invalid reflect.Value>
Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105867 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatal (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105811 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105341:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdirseek_testDirSeek [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48447:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1

-- FAIL: TestDirSeek

=== RUN  TestReaddirSmallSeek
Exception: ENOENT: no such file or directory, open '/home/runner/work/go2hx/go2hx/testdata/issue37161'
Called from Object.openSync (node:fs line 563 column 18)
Called from Object.writeFileSync (node:fs line 2441 column 35)
Called from .stdgo__$internal_os_Os_$openfile_openFile (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59691 column 14)
Called from .stdgo__$internal_os_Os_$open_open (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 60028 column 9)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreaddirsmallseek_testReaddirSmallSeek [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:54478:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)

-- FAIL: TestReaddirSmallSeek

=== RUN  TestOpenFileKeepsPermissions
Exception: File:os.stat is not yet implemented
Called from stdgo__$internal_os_File_$static_$extension.stat (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 42669 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testopenfilekeepspermissions_testOpenFileKeepsPermissions [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:52199:60)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestOpenFileKeepsPermissions

=== RUN  TestDirFS
Exception: ENOENT: no such file or directory, open 'testdata/dirfs'
Called from stdgo__$internal_testing_fstest_T_$fsTester_$static_$extension._checkDir (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 68389 column 25)
Called from .stdgo__$internal_testing_fstest_Fstest_$_$testfs__testFS (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66810 column 65)
Called from .stdgo__$internal_testing_fstest_Fstest_$testfs_testFS (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66760 column 70)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdirfs_testDirFS [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48169:13)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1

-- FAIL: TestDirFS

=== RUN  TestDirFSRootDir
Exception: ENOENT: no such file or directory, open '/home/runner/work/go2hx/go2hx/testdata/dirfs/a'
Called from Object.openSync (node:fs line 563 column 18)
Called from Object.writeFileSync (node:fs line 2441 column 35)
Called from .stdgo__$internal_os_Os_$openfile_openFile (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59691 column 14)
Called from .stdgo__$internal_os_Os_$open_open (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 60028 column 9)
Called from stdgo__$internal_os_T_$dirFS_$static_$extension.open (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 97674 column 12)
Called from stdgo__$internal_os_T_$dirFS_$asInterface.open (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66748 column 58)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdirfsrootdir_testDirFSRootDir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48427:20)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)

-- FAIL: TestDirFSRootDir

=== RUN  TestDirFSEmptyDir
Exception: ENOENT: no such file or directory, open 'testdata/dirfs/a'
Called from Object.openSync (node:fs line 563 column 18)
Called from Object.writeFileSync (node:fs line 2441 column 35)
Called from .stdgo__$internal_os_Os_$openfile_openFile (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59691 column 14)
Called from .stdgo__$internal_os_Os_$open_open (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 60028 column 9)
Called from stdgo__$internal_os_T_$dirFS_$static_$extension.open (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 97674 column 12)
Called from stdgo__$internal_os_T_$dirFS_$asInterface.open (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66748 column 58)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdirfsemptydir_testDirFSEmptyDir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48351:21)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)

-- FAIL: TestDirFSEmptyDir

=== RUN  TestDirFSPathsValid
<invalid reflect.Value>
Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105867 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatal (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105811 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105341:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdirfspathsvalid_testDirFSPathsValid [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48366:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1

-- FAIL: TestDirFSPathsValid

=== RUN  TestReadFileProc

-- PASS: TestReadFileProc

=== RUN  TestDirFSReadFileProc
Exception: T_dirFS:os.readFile is not yet implemented
Called from .stdgo__$internal_io_fs_Fs_$readfile_readFile (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 69016 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdirfsreadfileproc_testDirFSReadFileProc [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48397:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestDirFSReadFileProc

=== RUN  TestWriteStringAlloc
<invalid reflect.Value>
Exception: __skip__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testwritestringalloc_testWriteStringAlloc [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:59391:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- SKIP: TestWriteStringAlloc

-- PASS: TestWriteStringAlloc

=== RUN  TestPipeIOCloseRace
skipping on <invalid reflect.Value>: no pipesException: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105751 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105766 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105404:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testpipeiocloserace_testPipeIOCloseRace [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:52394:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1

-- SKIP: TestPipeIOCloseRace

-- PASS: TestPipeIOCloseRace

=== RUN  TestPipeCloseRace
skipping on <invalid reflect.Value>: no pipesException: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105751 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105766 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105404:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testpipecloserace_testPipeCloseRace [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:52275:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1

-- SKIP: TestPipeCloseRace

-- PASS: TestPipeCloseRace

=== RUN  TestChown
Exception: File:os.stat is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testchown_testChown [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:46885:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestChown

=== RUN  TestFileChown
Exception: File:os.stat is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testfilechown_testFileChown [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49314:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestFileChown

=== RUN  TestLchown
Exception: File:os.stat is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testlchown_testLchown [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50492:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestLchown

=== RUN  TestReaddirRemoveRace
Exception: invalid memory address or nil pointer dereference
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreaddirremoverace_testReaddirRemoveRace [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:54464:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestReaddirRemoveRace

=== RUN  TestMkdirStickyUmask
Exception: :syscall.umask is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testmkdirstickyumask_testMkdirStickyUmask [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51537:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestMkdirStickyUmask

=== RUN  TestNewFileBlock
syscall.Pipe is not available on <invalid reflect.Value>.Exception: __skip__
Called from ._$internal_os_$test_Os_$test_$_$newfiletest__newFileTest (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 44123 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testnewfileblock_testNewFileBlock [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51992:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- SKIP: TestNewFileBlock

-- PASS: TestNewFileBlock

=== RUN  TestNewFileNonBlock
syscall.Pipe is not available on <invalid reflect.Value>.Exception: __skip__
Called from ._$internal_os_$test_Os_$test_$_$newfiletest__newFileTest (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 44123 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testnewfilenonblock_testNewFileNonBlock [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:52018:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- SKIP: TestNewFileNonBlock

-- PASS: TestNewFileNonBlock

=== RUN  TestNewFileInvalid
Exception: :os.newFile is not yet implemented
Called from .stdgo__$internal_os_Os_$newfile_newFile (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 70555 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testnewfileinvalid_testNewFileInvalid [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51996:11)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestNewFileInvalid

=== RUN  TestSplitPath
Exception: stdgo__$internal_os_Os_$splitpath_splitPath is not a function
Called from module TypeError: stdgo__$internal_os_Os_$splitpath_splitPath is not a function
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testsplitpath_testSplitPath [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:57595:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)
Called from Function._load (node:internal/modules/cjs/loader line 1286 column 12)

-- FAIL: TestSplitPath

=== RUN  TestMkdirAll
Exception: :os.tempDir is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testmkdirall_testMkdirAll [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51221:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestMkdirAll

=== RUN  TestMkdirAllWithSymlink
Exception: :os.symlink is not yet implemented
Called from .stdgo__$internal_os_Os_$symlink_symlink (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 64739 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testmkdirallwithsymlink_testMkdirAllWithSymlink [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51420:13)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestMkdirAllWithSymlink

=== RUN  TestMkdirAllAtSlash
Exception: Cannot read properties of undefined (reading '_common')
Called from module TypeError: Cannot read properties of undefined (reading '_common')
Called from stdgo__$internal_internal_reflect__$Type_$static_$extension.string (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 23940 column 13)
Called from stdgo__$internal_internal_reflect__$Type_$asInterface.string (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 24358 column 70)
Called from stdgo__$internal_fmt_T_$pp_$static_$extension._doPrintf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 28488 column 141)
Called from .stdgo__$internal_fmt_Fmt_$fprintf_fprintf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 40539 column 48)
Called from .stdgo__$internal_fmt_Fmt_$printf_printf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 90075 column 51)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105765 column 42)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105404:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testmkdirallatslash_testMkdirAllAtSlash [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51234:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)

-- FAIL: TestMkdirAllAtSlash

=== RUN  TestReadFile
ReadFile <invalid reflect.Value>: %!v(MISSING)Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105867 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatalf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105796 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105350:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreadfile_testReadFile [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:54772:20)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1

-- FAIL: TestReadFile

=== RUN  TestWriteFile

-- PASS: TestWriteFile

=== RUN  TestReadOnlyWriteFile
Exception: :os.getuid is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreadonlywritefile_testReadOnlyWriteFile [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:54906:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestReadOnlyWriteFile

=== RUN  TestReadDir
Exception: ENOENT: no such file or directory, scandir 'rumpelstilzchen'
Called from Object.readdirSync (node:fs line 1581 column 26)
Called from .stdgo__$internal_os_Os_$readdir_readDir (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 70831 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreaddir_testReadDir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:53911:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestReadDir

=== RUN  TestRemoveAll
Exception: :os.mkdirAll is not yet implemented
Called from .stdgo__$internal_os_Os_$mkdirall_mkdirAll (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66545 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremoveall_testRemoveAll [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:54945:14)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestRemoveAll

=== RUN  TestRemoveAllLarge
<invalid reflect.Value>
Exception: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105751 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skip (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105781 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105389:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremovealllarge_testRemoveAllLarge [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:55425:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1

-- SKIP: TestRemoveAllLarge

-- PASS: TestRemoveAllLarge

=== RUN  TestRemoveAllLongPath
<invalid reflect.Value>
Exception: __skip__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremovealllongpath_testRemoveAllLongPath [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:55580:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- SKIP: TestRemoveAllLongPath

-- PASS: TestRemoveAllLongPath

=== RUN  TestRemoveAllDot
Exception: EINVAL: invalid argument, rmdir '.'
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremovealldot_testRemoveAllDot [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:55388:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestRemoveAllDot

=== RUN  TestRemoveAllDotDot
Exception: :os.mkdirAll is not yet implemented
Called from .stdgo__$internal_os_Os_$mkdirall_mkdirAll (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66545 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremovealldotdot_testRemoveAllDotDot [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:55401:13)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestRemoveAllDotDot

=== RUN  TestRemoveReadOnlyDir
chmod: cannot access 'tmp_uiijt0u89i/x': No such file or directory

-- PASS: TestRemoveReadOnlyDir

=== RUN  TestRemoveAllButReadOnlyAndPathError
skipping test on <invalid reflect.Value>Exception: __skip__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremoveallbutreadonlyandpatherror_testRemoveAllButReadOnlyAndPathError [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:55287:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- SKIP: TestRemoveAllButReadOnlyAndPathError

-- PASS: TestRemoveAllButReadOnlyAndPathError

=== RUN  TestRemoveUnreadableDir
skipping test on <invalid reflect.Value>Exception: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105751 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105766 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105404:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremoveunreadabledir_testRemoveUnreadableDir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:56097:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1

-- SKIP: TestRemoveUnreadableDir

-- PASS: TestRemoveUnreadableDir

=== RUN  TestRemoveAllWithMoreErrorThanReqSize
<invalid reflect.Value>
Exception: __skip__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremoveallwithmoreerrorthanreqsize_testRemoveAllWithMoreErrorThanReqSize [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:55994:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- SKIP: TestRemoveAllWithMoreErrorThanReqSize

-- PASS: TestRemoveAllWithMoreErrorThanReqSize

=== RUN  TestRemoveAllNoFcntl
<invalid reflect.Value>
Exception: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105751 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skip (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105781 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105389:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremoveallnofcntl_testRemoveAllNoFcntl [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:55587:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1

-- SKIP: TestRemoveAllNoFcntl

-- PASS: TestRemoveAllNoFcntl

=== RUN  TestDirAndSymlinkStats
Exception: :os.sameFile is not yet implemented
Called from ._$internal_os_$test_Os_$test_$_$teststatandlstat__testStatAndLstat (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 45861 column 25)
Called from ._$internal_os_$test_Os_$test_$_$testdirstats__testDirStats (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 44673 column 2)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdirandsymlinkstats_testDirAndSymlinkStats [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48146:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)

-- FAIL: TestDirAndSymlinkStats

=== RUN  TestFileAndSymlinkStats
<invalid reflect.Value>
Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105867 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatal (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105811 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:105341:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testfileandsymlinkstats_testFileAndSymlinkStats [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48981:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1

-- FAIL: TestFileAndSymlinkStats

=== RUN  TestSymlinkWithTrailingSlash
Exception: :os.symlink is not yet implemented
Called from .stdgo__$internal_os_Os_$symlink_symlink (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 64739 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testsymlinkwithtrailingslash_testSymlinkWithTrailingSlash [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:58595:13)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestSymlinkWithTrailingSlash

=== RUN  TestCreateTemp
Exception: ENOENT: no such file or directory, open 'TestCreateTempBadDirtmp_55h6no1n4u/_not_exists_/tmp_54rvtzq6fv'
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testcreatetemp_testCreateTemp [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:47781:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestCreateTemp

=== RUN  TestCreateTempPattern
CreateTemp pattern <invalid reflect.Value> created bad name %!q(MISSING); want prefix %!q(MISSING) & suffix %!q(MISSING)
CreateTemp pattern <invalid reflect.Value> created bad name %!q(MISSING); want prefix %!q(MISSING) & suffix %!q(MISSING)
CreateTemp pattern <invalid reflect.Value> created bad name %!q(MISSING); want prefix %!q(MISSING) & suffix %!q(MISSING)

-- FAIL: TestCreateTempPattern

=== RUN  TestCreateTempBadPattern
Exception: T_common:testing.name is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testcreatetempbadpattern_testCreateTempBadPattern [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:47986:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestCreateTempBadPattern

=== RUN  TestMkdirTemp
MkdirTemp(`/_not_exists_`, `foo`) = <invalid reflect.Value>, %!v(MISSING)
Exception: :os.tempDir is not yet implemented
Called from .stdgo__$internal_os_Os_$tempdir_tempDir (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 65419 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testmkdirtemp_testMkdirTemp [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51572:12)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestMkdirTemp

=== RUN  TestMkdirTempBadDir
TempDir error = <invalid reflect.Value>; want PathError for path %!q(MISSING) satisfying IsNotExist

-- FAIL: TestMkdirTempBadDir

=== RUN  TestMkdirTempBadPattern
Exception: T_common:testing.name is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testmkdirtempbadpattern_testMkdirTempBadPattern [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51985:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 105112 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50929 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92758 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestMkdirTempBadPattern

./stdgo/_internal/testing/Testing_m_static_extension.hx:92: exitCode: 1 exitCodeReason: 
-- FAIL: TestMkdirTempBadPattern

/home/runner/work/go2hx/go2hx/golibs/std_os.js:65889
	throw haxe_Exception.thrown(":os.exit is not yet implemented");
	^
<ref *1> Error: :os.exit is not yet implemented
    at new haxe_ValueException (/home/runner/work/go2hx/go2hx/golibs/std_os.js:34025:17)
    at haxe_Exception.thrown (/home/runner/work/go2hx/go2hx/golibs/std_os.js:33955:11)
    at stdgo__$internal_os_Os_$exit_exit (/home/runner/work/go2hx/go2hx/golibs/std_os.js:65889:23)
    at _$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50929:2)
    at _$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js:92758:2)
    at /home/runner/work/go2hx/go2hx/golibs/std_os.js:117645:1
    at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:117646:3)
    at Module._compile (node:internal/modules/cjs/loader:1734:14)
    at Object..js (node:internal/modules/cjs/loader:1899:10)
    at Module.load (node:internal/modules/cjs/loader:1469:32) {
  __previousException: undefined,
  __nativeException: [Circular *1],
  __skipStack: 2,
  value: ':os.exit is not yet implemented'
}

Node.js v23.11.0
