=== RUN  TestExpand
Exception: :os.expand is not yet implemented
Called from .stdgo__$internal_os_Os_$expand_expand (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59087 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testexpand_testExpand [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48646:14)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestExpand

=== RUN  TestConsistentEnviron

-- PASS: TestConsistentEnviron

=== RUN  TestUnsetenv
Exception: :os.setenv is not yet implemented
Called from .stdgo__$internal_os_Os_$setenv_setenv (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59149 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testunsetenv_testUnsetenv [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:58537:13)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestUnsetenv

=== RUN  TestClearenv
Exception: :os.setenv is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testclearenv_testClearenv [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:47349:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestClearenv

=== RUN  TestLookupEnv
Exception: :os.lookupEnv is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testlookupenv_testLookupEnv [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50573:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestLookupEnv

=== RUN  TestEnvironConsistency

-- PASS: TestEnvironConsistency

=== RUN  TestErrIsExist
<invalid reflect.Value>
Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testerrisexist_testErrIsExist [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48323:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestErrIsExist

=== RUN  TestErrIsNotExist
<invalid reflect.Value>
Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 104073 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatal (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 104024 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103562:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testerrisnotexist_testErrIsNotExist [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48337:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1

-- FAIL: TestErrIsNotExist

=== RUN  TestIsExist
Exception: :os.isExist is not yet implemented
Called from .stdgo__$internal_os_Os_$isexist_isExist (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59713 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testisexist_testIsExist [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49747:13)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestIsExist

=== RUN  TestIsPermission
Exception: :os.isPermission is not yet implemented
Called from .stdgo__$internal_os_Os_$ispermission_isPermission (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59722 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testispermission_testIsPermission [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49771:14)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestIsPermission

=== RUN  TestErrPathNUL
<invalid reflect.Value>
Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testerrpathnul_testErrPathNUL [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48479:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestErrPathNUL

=== RUN  TestPathErrorUnwrap

-- PASS: TestPathErrorUnwrap

=== RUN  TestErrorIsMethods
Exception: :os.isPermission is not yet implemented
Called from .stdgo__$internal_os_Os_$ispermission_isPermission (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59722 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testerrorismethods_testErrorIsMethods [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48350:5)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestErrorIsMethods

=== RUN  TestExecutable
Exception: :os.executable is not yet implemented
Called from .stdgo__$internal_os_Os_$executable_executable (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 42660 column 23)
Called from .stdgo__$internal_internal_testenv_Testenv_$_$tryexec__tryExec (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59778 column 16)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:59726:73
Called from stdgo__$internal_sync_Once_$static_$extension.do_ (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59747 column 2)
Called from .stdgo__$internal_internal_testenv_Testenv_$musthaveexec_mustHaveExec (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59725 column 48)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testexecutable_testExecutable [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48485:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)

-- FAIL: TestExecutable

=== RUN  TestExecutableDeleted
skipping test: 'go build' unavailable: <invalid reflect.Value>Exception: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103968 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103982 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103625:58
Called from stdgo__$internal_testing_T_$_$asInterface.skipf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59959 column 54)
Called from .stdgo__$internal_internal_testenv_Testenv_$musthavegobuild_mustHaveGoBuild (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 63049 column 6)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testexecutabledeleted_testExecutableDeleted [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48572:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)

-- SKIP: TestExecutableDeleted

-- PASS: TestExecutableDeleted

=== RUN  TestStat
<invalid reflect.Value>
<invalid reflect.Value>
Exception: __fail__
Called from ._$internal_os_$test_Os_$test_$_$size__size (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 44052 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$teststat_testStat [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:57357:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestStat

=== RUN  TestStatError
Exception: Cannot read properties of undefined (reading '_common')
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$teststaterror_testStatError [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:57678:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestStatError

=== RUN  TestStatSymlinkLoop
Exception: :os.symlink is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$teststatsymlinkloop_testStatSymlinkLoop [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:58061:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestStatSymlinkLoop

=== RUN  TestFstat
<invalid reflect.Value>
Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testfstat_testFstat [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49185:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestFstat

=== RUN  TestLstat
<invalid reflect.Value>
<invalid reflect.Value>
Exception: __fail__
Called from ._$internal_os_$test_Os_$test_$_$size__size (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 44052 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testlstat_testLstat [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50599:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestLstat

=== RUN  TestRead0
<invalid reflect.Value>
Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testread0_testRead0 [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:53049:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestRead0

=== RUN  TestReadClosed
<invalid reflect.Value>
Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 104073 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatal (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 104024 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103562:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreadclosed_testReadClosed [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:53476:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1

-- FAIL: TestReadClosed

=== RUN  TestFileReaddirnames
- SUBRUN  .
open <invalid reflect.Value> failed: %!v(MISSING)Exception: __fail__
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:45196:26
Called from stdgo__$internal_testing_T_$_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59171 column 2)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testfilereaddirnames_testFileReaddirnames [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49061:50)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)

-- FAIL: TestFileReaddirnames

=== RUN  TestFileReaddir
- SUBRUN  .
open <invalid reflect.Value> failed: %!v(MISSING)Exception: __fail__
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:44885:26
Called from stdgo__$internal_testing_T_$_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59171 column 2)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testfilereaddir_testFileReaddir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49011:50)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)

-- FAIL: TestFileReaddir

=== RUN  TestFileReadDir
- SUBRUN  .
open <invalid reflect.Value> failed: %!v(MISSING)Exception: __fail__
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:45075:26
Called from stdgo__$internal_testing_T_$_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59171 column 2)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testfilereaddir_testFileReadDir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49036:50)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)

-- FAIL: TestFileReadDir

=== RUN  TestReaddirnamesOneAtATime
open <invalid reflect.Value> failed: %!v(MISSING)Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreaddirnamesoneatatime_testReaddirnamesOneAtATime [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:53765:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestReaddirnamesOneAtATime

=== RUN  TestReaddirNValues
<invalid reflect.Value>
Exception: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103968 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skip (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103996 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103610:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreaddirnvalues_testReaddirNValues [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:53772:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1

-- SKIP: TestReaddirNValues

-- PASS: TestReaddirNValues

=== RUN  TestReaddirStatFailures
Exception: Cannot read properties of null (reading 'previous')
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreaddirstatfailures_testReaddirStatFailures [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:54443:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestReaddirStatFailures

=== RUN  TestReaddirOfFile
Exception: File:os.readdirnames is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreaddiroffile_testReaddirOfFile [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:53995:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestReaddirOfFile

=== RUN  TestHardLink
skipping test: hardlinks are not supported on <invalid reflect.Value>/%!s(MISSING)Exception: __skip__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testhardlink_testHardLink [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49690:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- SKIP: TestHardLink

-- PASS: TestHardLink

=== RUN  TestSymlink
Exception: :os.symlink is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testsymlink_testSymlink [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:58260:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestSymlink

=== RUN  TestLongSymlink
Exception: :os.symlink is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testlongsymlink_testLongSymlink [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50476:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestLongSymlink

=== RUN  TestRename
Exception: :os.rename is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testrename_testRename [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:55903:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestRename

=== RUN  TestRenameOverwriteDest
write file <invalid reflect.Value> failed: %!v(MISSING)Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testrenameoverwritedest_testRenameOverwriteDest [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:56448:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestRenameOverwriteDest

=== RUN  TestRenameFailed
Exception: :os.rename is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testrenamefailed_testRenameFailed [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:56256:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestRenameFailed

=== RUN  TestRenameNotExisting
Exception: :os.rename is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testrenamenotexisting_testRenameNotExisting [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:56339:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestRenameNotExisting

=== RUN  TestRenameToDirFailed
Exception: :os.rename is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testrenametodirfailed_testRenameToDirFailed [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:56655:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestRenameToDirFailed

=== RUN  TestRenameCaseDifference
- SUBRUN  dir
Exception: :os.isNotExist is not yet implemented
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:56048:28
Called from stdgo__$internal_testing_T_$_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59171 column 2)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testrenamecasedifference_testRenameCaseDifference [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:55938:51)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)

-- FAIL: TestRenameCaseDifference

=== RUN  TestStartProcess
golibs/stdgo/_internal/os/exec/Exec_lookpath.hx:3: funclit
Exception: not implemented: lookPath
Called from .stdgo__$internal_os_exec_Exec_$lookpath_lookPath (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 63109 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$teststartprocess_testStartProcess [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:57317:17)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestStartProcess

=== RUN  TestChmod
Stat <invalid reflect.Value>: mode %!o(MISSING) want %!o(MISSING)
Exception: File:os.chmod is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testchmod_testChmod [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:46368:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestChmod

=== RUN  TestFTruncate
Exception: File:os.stat is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testftruncate_testFTruncate [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49284:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestFTruncate

=== RUN  TestTruncate
Exception: File:os.stat is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testtruncate_testTruncate [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:58408:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestTruncate

=== RUN  TestTruncateNonexistentFile
golibs/stdgo/_internal/os/Os_truncate.hx:3: os.truncate not implemented
got error: <invalid reflect.Value>
want an ErrNotExist PathError with path %!q(MISSING)
got error: <invalid reflect.Value>
want an ErrNotExist PathError with path %!q(MISSING)

-- FAIL: TestTruncateNonexistentFile

=== RUN  TestChtimes
Exception: stdgo__$internal_os_Os_$atime_atime is not a function
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testchtimes_testChtimes [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:46656:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestChtimes

=== RUN  TestChtimesWithZeroTimes
Exception: stdgo__$internal_os_Os_$atime_atime is not a function
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testchtimeswithzerotimes_testChtimesWithZeroTimes [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:47241:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestChtimesWithZeroTimes

=== RUN  TestChtimesDir
Exception: stdgo__$internal_os_Os_$atime_atime is not a function
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testchtimesdir_testChtimesDir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:46735:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestChtimesDir

=== RUN  TestChtimesToUnixZero
Exception: :os.chtimes is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testchtimestounixzero_testChtimesToUnixZero [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:46860:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestChtimesToUnixZero

=== RUN  TestFileChdir
Open .: <invalid reflect.Value>Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testfilechdir_testFileChdir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48799:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestFileChdir

=== RUN  TestChdirAndGetwd
Open .: <invalid reflect.Value>Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 104073 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatalf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 104010 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103571:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testchdirandgetwd_testChdirAndGetwd [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:46166:20)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1

-- FAIL: TestChdirAndGetwd

=== RUN  TestProgWideChdir

-- PASS: TestProgWideChdir

=== RUN  TestSeek
#<invalid reflect.Value>: Seek(%!v(MISSING), %!v(MISSING)) = %!v(MISSING), %!v(MISSING) want %!v(MISSING), nil
#<invalid reflect.Value>: Seek(%!v(MISSING), %!v(MISSING)) = %!v(MISSING), %!v(MISSING) want %!v(MISSING), nil
#<invalid reflect.Value>: Seek(%!v(MISSING), %!v(MISSING)) = %!v(MISSING), %!v(MISSING) want %!v(MISSING), nil
#<invalid reflect.Value>: Seek(%!v(MISSING), %!v(MISSING)) = %!v(MISSING), %!v(MISSING) want %!v(MISSING), nil
#<invalid reflect.Value>: Seek(%!v(MISSING), %!v(MISSING)) = %!v(MISSING), %!v(MISSING) want %!v(MISSING), nil
#<invalid reflect.Value>: Seek(%!v(MISSING), %!v(MISSING)) = %!v(MISSING), %!v(MISSING) want %!v(MISSING), nil
#<invalid reflect.Value>: Seek(%!v(MISSING), %!v(MISSING)) = %!v(MISSING), %!v(MISSING) want %!v(MISSING), nil

-- FAIL: TestSeek

=== RUN  TestSeekError
skipping test on <invalid reflect.Value>Exception: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103968 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103982 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103625:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testseekerror_testSeekError [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:57021:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1

-- SKIP: TestSeekError

-- PASS: TestSeekError

=== RUN  TestOpenError
Exception: EACCES: permission denied, open '/etc/no-such-file'
Called from Object.openSync (node:fs line 563 column 18)
Called from Object.writeFileSync (node:fs line 2441 column 35)
Called from .stdgo__$internal_os_Os_$openfile_openFile (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59379 column 14)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testopenerror_testOpenError [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51740:17)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestOpenError

=== RUN  TestOpenNoName
Exception: ENOENT: no such file or directory, open ''
Called from Object.openSync (node:fs line 563 column 18)
Called from Object.writeFileSync (node:fs line 2441 column 35)
Called from .stdgo__$internal_os_Os_$openfile_openFile (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59379 column 14)
Called from .stdgo__$internal_os_Os_$open_open (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59716 column 9)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testopennoname_testOpenNoName [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51943:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)

-- FAIL: TestOpenNoName

=== RUN  TestHostname
Exception: :os.hostname is not yet implemented
Called from .stdgo__$internal_os_Os_$hostname_hostname (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 65771 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testhostname_testHostname [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49697:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestHostname

=== RUN  TestReadAt

-- PASS: TestReadAt

=== RUN  TestReadAtOffset

-- PASS: TestReadAtOffset

=== RUN  TestReadAtNegativeOffset
ReadAt(-10) = <invalid reflect.Value>, %!v(MISSING); want 0, ...%!q(MISSING)...

-- FAIL: TestReadAtNegativeOffset

=== RUN  TestWriteAt

-- PASS: TestWriteAt

=== RUN  TestWriteAtNegativeOffset
WriteAt(-10) = <invalid reflect.Value>, %!v(MISSING); want 0, ...%!q(MISSING)...

-- FAIL: TestWriteAtNegativeOffset

=== RUN  TestWriteAtInAppendMode

-- PASS: TestWriteAtInAppendMode

=== RUN  TestAppend
writeFile: have <invalid reflect.Value> want %!q(MISSING)Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testappend_testAppend [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:46156:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestAppend

=== RUN  TestStatDirWithTrailingSlash

-- PASS: TestStatDirWithTrailingSlash

=== RUN  TestNilProcessStateString
Exception: ProcessState:os.string is not yet implemented
Called from stdgo__$internal_os_ProcessState_$static_$extension.string (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66035 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testnilprocessstatestring_testNilProcessStateString [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51726:64)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestNilProcessStateString

=== RUN  TestSameFile
Exception: :os.sameFile is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testsamefile_testSameFile [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:56767:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestSameFile

=== RUN  TestDevNullFile
Exception: File:os.stat is not yet implemented
Called from ._$internal_os_$test_Os_$test_$_$testdevnullfile__testDevNullFile (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 44284 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdevnullfile_testDevNullFile [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:47816:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestDevNullFile

=== RUN  TestLargeWriteToConsole
<invalid reflect.Value>
Exception: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103968 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skip (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103996 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103610:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testlargewritetoconsole_testLargeWriteToConsole [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49812:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1

-- SKIP: TestLargeWriteToConsole

-- PASS: TestLargeWriteToConsole

=== RUN  TestStatDirModeExec
Stat <invalid reflect.Value>: mode %!o(MISSING) want %!o(MISSING)

-- FAIL: TestStatDirModeExec

=== RUN  TestStatStdin
Exception: File:os.stat is not yet implemented
Called from stdgo__$internal_os_File_$static_$extension.stat (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 42363 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$teststatstdin_testStatStdin [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:57838:60)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestStatStdin

=== RUN  TestStatRelativeSymlink
Exception: File:os.stat is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$teststatrelativesymlink_testStatRelativeSymlink [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:57796:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestStatRelativeSymlink

=== RUN  TestReadAtEOF
ReadAt failed: <invalid reflect.Value>Exception: __fail__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreadateof_testReadAtEOF [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:53246:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestReadAtEOF

=== RUN  TestLongPath
- SUBRUN  length=247
Exception: :os.mkdirAll is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testlongpath_testLongPath [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50377:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestLongPath

=== RUN  TestKillStartProcess
Exception: :context.background is not yet implemented
Called from ._$internal_os_$test_Os_$test_$_$testkillprocess__testKillProcess (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 44763 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testkillstartprocess_testKillStartProcess [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49803:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestKillStartProcess

=== RUN  TestGetppid
Exception: :context.background is not yet implemented
Called from .stdgo__$internal_context_Context_$background_background (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 63030 column 23)
Called from .stdgo__$internal_internal_testenv_Testenv_$command_command (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 60156 column 97)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testgetppid_testGetppid [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49312:14)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)

-- FAIL: TestGetppid

=== RUN  TestKillFindProcess
Exception: :context.background is not yet implemented
Called from ._$internal_os_$test_Os_$test_$_$testkillprocess__testKillProcess (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 44763 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testkillfindprocess_testKillFindProcess [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49782:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestKillFindProcess

=== RUN  TestNilFileMethods
Exception: File:os.chdir is not yet implemented
Called from stdgo__$internal_os_File_$static_$extension.chdir (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 42387 column 23)
Called from Object._f (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 109334 column 54)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testnilfilemethods_testNilFileMethods [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51718:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)

-- FAIL: TestNilFileMethods

=== RUN  TestRemoveAllRace

-- PASS: TestRemoveAllRace

=== RUN  TestPipeThreads
<invalid reflect.Value>
Exception: __skip__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testpipethreads_testPipeThreads [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:52621:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- SKIP: TestPipeThreads

-- PASS: TestPipeThreads

=== RUN  TestDoubleCloseError
- SUBRUN  file
<invalid reflect.Value>
Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 104073 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatal (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 104024 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103562:58
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:44369:20
Called from stdgo__$internal_testing_T_$_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59171 column 2)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdoublecloseerror_testDoubleCloseError [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48182:50)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)

-- FAIL: TestDoubleCloseError

=== RUN  TestUserHomeDir
Exception: :os.userHomeDir is not yet implemented
Called from .stdgo__$internal_os_Os_$userhomedir_userHomeDir (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66178 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testuserhomedir_testUserHomeDir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:58554:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestUserHomeDir

=== RUN  TestDirSeek
<invalid reflect.Value>
Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 104073 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatal (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 104024 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103562:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdirseek_testDirSeek [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48137:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1

-- FAIL: TestDirSeek

=== RUN  TestReaddirSmallSeek
Exception: ENOENT: no such file or directory, open '/home/runner/work/go2hx/go2hx/testdata/issue37161'
Called from Object.openSync (node:fs line 563 column 18)
Called from Object.writeFileSync (node:fs line 2441 column 35)
Called from .stdgo__$internal_os_Os_$openfile_openFile (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59379 column 14)
Called from .stdgo__$internal_os_Os_$open_open (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59716 column 9)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreaddirsmallseek_testReaddirSmallSeek [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:54168:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)

-- FAIL: TestReaddirSmallSeek

=== RUN  TestOpenFileKeepsPermissions
Exception: File:os.stat is not yet implemented
Called from stdgo__$internal_os_File_$static_$extension.stat (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 42363 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testopenfilekeepspermissions_testOpenFileKeepsPermissions [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51889:60)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestOpenFileKeepsPermissions

=== RUN  TestDirFS
Exception: ENOENT: no such file or directory, open 'testdata/dirfs'
Called from stdgo__$internal_testing_fstest_T_$fsTester_$static_$extension._checkDir (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 67977 column 25)
Called from .stdgo__$internal_testing_fstest_Fstest_$_$testfs__testFS (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66398 column 65)
Called from .stdgo__$internal_testing_fstest_Fstest_$testfs_testFS (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66348 column 70)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdirfs_testDirFS [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:47859:13)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1

-- FAIL: TestDirFS

=== RUN  TestDirFSRootDir
Exception: ENOENT: no such file or directory, open '/home/runner/work/go2hx/go2hx/testdata/dirfs/a'
Called from Object.openSync (node:fs line 563 column 18)
Called from Object.writeFileSync (node:fs line 2441 column 35)
Called from .stdgo__$internal_os_Os_$openfile_openFile (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59379 column 14)
Called from .stdgo__$internal_os_Os_$open_open (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59716 column 9)
Called from stdgo__$internal_os_T_$dirFS_$static_$extension.open (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 97112 column 12)
Called from stdgo__$internal_os_T_$dirFS_$asInterface.open (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66336 column 58)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdirfsrootdir_testDirFSRootDir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48117:20)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)

-- FAIL: TestDirFSRootDir

=== RUN  TestDirFSEmptyDir
Exception: ENOENT: no such file or directory, open 'testdata/dirfs/a'
Called from Object.openSync (node:fs line 563 column 18)
Called from Object.writeFileSync (node:fs line 2441 column 35)
Called from .stdgo__$internal_os_Os_$openfile_openFile (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59379 column 14)
Called from .stdgo__$internal_os_Os_$open_open (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 59716 column 9)
Called from stdgo__$internal_os_T_$dirFS_$static_$extension.open (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 97112 column 12)
Called from stdgo__$internal_os_T_$dirFS_$asInterface.open (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66336 column 58)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdirfsemptydir_testDirFSEmptyDir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48041:21)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)

-- FAIL: TestDirFSEmptyDir

=== RUN  TestDirFSPathsValid
<invalid reflect.Value>
Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 104073 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatal (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 104024 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103562:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdirfspathsvalid_testDirFSPathsValid [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48056:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1

-- FAIL: TestDirFSPathsValid

=== RUN  TestReadFileProc

-- PASS: TestReadFileProc

=== RUN  TestDirFSReadFileProc
Exception: T_dirFS:os.readFile is not yet implemented
Called from .stdgo__$internal_io_fs_Fs_$readfile_readFile (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 68604 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdirfsreadfileproc_testDirFSReadFileProc [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48087:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestDirFSReadFileProc

=== RUN  TestWriteStringAlloc
<invalid reflect.Value>
Exception: __skip__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testwritestringalloc_testWriteStringAlloc [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:59081:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- SKIP: TestWriteStringAlloc

-- PASS: TestWriteStringAlloc

=== RUN  TestPipeIOCloseRace
skipping on <invalid reflect.Value>: no pipesException: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103968 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103982 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103625:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testpipeiocloserace_testPipeIOCloseRace [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:52084:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1

-- SKIP: TestPipeIOCloseRace

-- PASS: TestPipeIOCloseRace

=== RUN  TestPipeCloseRace
skipping on <invalid reflect.Value>: no pipesException: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103968 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103982 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103625:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testpipecloserace_testPipeCloseRace [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51965:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1

-- SKIP: TestPipeCloseRace

-- PASS: TestPipeCloseRace

=== RUN  TestChown
Exception: File:os.stat is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testchown_testChown [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:46575:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestChown

=== RUN  TestFileChown
Exception: File:os.stat is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testfilechown_testFileChown [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:49004:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestFileChown

=== RUN  TestLchown
Exception: File:os.stat is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testlchown_testLchown [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50182:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestLchown

=== RUN  TestReaddirRemoveRace
Exception: invalid memory address or nil pointer dereference
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreaddirremoverace_testReaddirRemoveRace [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:54154:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestReaddirRemoveRace

=== RUN  TestMkdirStickyUmask
Exception: :syscall.umask is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testmkdirstickyumask_testMkdirStickyUmask [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51227:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestMkdirStickyUmask

=== RUN  TestNewFileBlock
syscall.Pipe is not available on <invalid reflect.Value>.Exception: __skip__
Called from ._$internal_os_$test_Os_$test_$_$newfiletest__newFileTest (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 43810 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testnewfileblock_testNewFileBlock [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51682:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- SKIP: TestNewFileBlock

-- PASS: TestNewFileBlock

=== RUN  TestNewFileNonBlock
syscall.Pipe is not available on <invalid reflect.Value>.Exception: __skip__
Called from ._$internal_os_$test_Os_$test_$_$newfiletest__newFileTest (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 43810 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testnewfilenonblock_testNewFileNonBlock [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51708:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- SKIP: TestNewFileNonBlock

-- PASS: TestNewFileNonBlock

=== RUN  TestNewFileInvalid
Exception: :os.newFile is not yet implemented
Called from .stdgo__$internal_os_Os_$newfile_newFile (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 70143 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testnewfileinvalid_testNewFileInvalid [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51686:11)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestNewFileInvalid

=== RUN  TestSplitPath
Exception: stdgo__$internal_os_Os_$splitpath_splitPath is not a function
Called from module TypeError: stdgo__$internal_os_Os_$splitpath_splitPath is not a function
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testsplitpath_testSplitPath [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:57285:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)
Called from Module.load (node:internal/modules/cjs/loader line 1469 column 32)
Called from Function._load (node:internal/modules/cjs/loader line 1286 column 12)

-- FAIL: TestSplitPath

=== RUN  TestMkdirAll
Exception: :os.mkdirAll is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testmkdirall_testMkdirAll [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50911:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestMkdirAll

=== RUN  TestMkdirAllWithSymlink
Exception: :os.symlink is not yet implemented
Called from .stdgo__$internal_os_Os_$symlink_symlink (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 64333 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testmkdirallwithsymlink_testMkdirAllWithSymlink [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51110:13)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestMkdirAllWithSymlink

=== RUN  TestMkdirAllAtSlash
Exception: Cannot read properties of undefined (reading '_common')
Called from module TypeError: Cannot read properties of undefined (reading '_common')
Called from stdgo__$internal_internal_reflect__$Type_$static_$extension.string (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 23656 column 13)
Called from stdgo__$internal_internal_reflect__$Type_$asInterface.string (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 24074 column 70)
Called from stdgo__$internal_fmt_T_$pp_$static_$extension._doPrintf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 28204 column 141)
Called from .stdgo__$internal_fmt_Fmt_$fprintf_fprintf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 40233 column 48)
Called from .stdgo__$internal_fmt_Fmt_$printf_printf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 89659 column 51)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103981 column 42)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103625:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testmkdirallatslash_testMkdirAllAtSlash [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50924:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)

-- FAIL: TestMkdirAllAtSlash

=== RUN  TestReadFile
ReadFile <invalid reflect.Value>: %!v(MISSING)Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 104073 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatalf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 104010 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103571:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreadfile_testReadFile [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:54462:20)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1

-- FAIL: TestReadFile

=== RUN  TestWriteFile

-- PASS: TestWriteFile

=== RUN  TestReadOnlyWriteFile
Exception: :os.getuid is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreadonlywritefile_testReadOnlyWriteFile [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:54596:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestReadOnlyWriteFile

=== RUN  TestReadDir
Exception: ENOENT: no such file or directory, scandir 'rumpelstilzchen'
Called from Object.readdirSync (node:fs line 1581 column 26)
Called from .stdgo__$internal_os_Os_$readdir_readDir (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 70419 column 25)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testreaddir_testReadDir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:53601:16)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestReadDir

=== RUN  TestRemoveAll
Exception: :os.mkdirAll is not yet implemented
Called from .stdgo__$internal_os_Os_$mkdirall_mkdirAll (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66132 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremoveall_testRemoveAll [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:54635:14)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestRemoveAll

=== RUN  TestRemoveAllLarge
<invalid reflect.Value>
Exception: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103968 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skip (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103996 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103610:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremovealllarge_testRemoveAllLarge [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:55115:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1

-- SKIP: TestRemoveAllLarge

-- PASS: TestRemoveAllLarge

=== RUN  TestRemoveAllLongPath
<invalid reflect.Value>
Exception: __skip__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremovealllongpath_testRemoveAllLongPath [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:55270:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- SKIP: TestRemoveAllLongPath

-- PASS: TestRemoveAllLongPath

=== RUN  TestRemoveAllDot
Exception: EINVAL: invalid argument, rmdir '.'
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremovealldot_testRemoveAllDot [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:55078:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestRemoveAllDot

=== RUN  TestRemoveAllDotDot
Exception: :os.mkdirAll is not yet implemented
Called from .stdgo__$internal_os_Os_$mkdirall_mkdirAll (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 66132 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremovealldotdot_testRemoveAllDotDot [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:55091:13)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestRemoveAllDotDot

=== RUN  TestRemoveReadOnlyDir
chmod: cannot access 'tmp_xyr10mb94x/x': No such file or directory

-- PASS: TestRemoveReadOnlyDir

=== RUN  TestRemoveAllButReadOnlyAndPathError
skipping test on <invalid reflect.Value>Exception: __skip__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremoveallbutreadonlyandpatherror_testRemoveAllButReadOnlyAndPathError [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:54977:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- SKIP: TestRemoveAllButReadOnlyAndPathError

-- PASS: TestRemoveAllButReadOnlyAndPathError

=== RUN  TestRemoveUnreadableDir
skipping test on <invalid reflect.Value>Exception: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103968 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipf (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103982 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103625:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremoveunreadabledir_testRemoveUnreadableDir [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:55787:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1

-- SKIP: TestRemoveUnreadableDir

-- PASS: TestRemoveUnreadableDir

=== RUN  TestRemoveAllWithMoreErrorThanReqSize
<invalid reflect.Value>
Exception: __skip__
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremoveallwithmoreerrorthanreqsize_testRemoveAllWithMoreErrorThanReqSize [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:55684:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- SKIP: TestRemoveAllWithMoreErrorThanReqSize

-- PASS: TestRemoveAllWithMoreErrorThanReqSize

=== RUN  TestRemoveAllNoFcntl
<invalid reflect.Value>
Exception: __skip__
Called from stdgo__$internal_testing_T_$common_$static_$extension.skipNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103968 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.skip (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103996 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103610:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testremoveallnofcntl_testRemoveAllNoFcntl [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:55277:18)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1

-- SKIP: TestRemoveAllNoFcntl

-- PASS: TestRemoveAllNoFcntl

=== RUN  TestDirAndSymlinkStats
Exception: :os.sameFile is not yet implemented
Called from ._$internal_os_$test_Os_$test_$_$teststatandlstat__testStatAndLstat (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 45548 column 25)
Called from ._$internal_os_$test_Os_$test_$_$testdirstats__testDirStats (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 44360 column 2)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testdirandsymlinkstats_testDirAndSymlinkStats [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:47836:2)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)

-- FAIL: TestDirAndSymlinkStats

=== RUN  TestFileAndSymlinkStats
<invalid reflect.Value>
Exception: __fail__
Called from stdgo__$internal_testing_T_$common_$static_$extension.failNow (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 104073 column 23)
Called from stdgo__$internal_testing_T_$common_$static_$extension.fatal (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 104024 column 56)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:103562:58
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testfileandsymlinkstats_testFileAndSymlinkStats [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:48671:19)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1

-- FAIL: TestFileAndSymlinkStats

=== RUN  TestSymlinkWithTrailingSlash
Exception: :os.symlink is not yet implemented
Called from .stdgo__$internal_os_Os_$symlink_symlink (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 64333 column 23)
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testsymlinkwithtrailingslash_testSymlinkWithTrailingSlash [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:58285:13)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)

-- FAIL: TestSymlinkWithTrailingSlash

=== RUN  TestCreateTemp
Exception: ENOENT: no such file or directory, open 'TestCreateTempBadDirtmp_3ss8522e6e/_not_exists_/tmp_6857jxb7v9'
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testcreatetemp_testCreateTemp [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:47471:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestCreateTemp

=== RUN  TestCreateTempPattern
CreateTemp pattern <invalid reflect.Value> created bad name %!q(MISSING); want prefix %!q(MISSING) & suffix %!q(MISSING)
CreateTemp pattern <invalid reflect.Value> created bad name %!q(MISSING); want prefix %!q(MISSING) & suffix %!q(MISSING)
CreateTemp pattern <invalid reflect.Value> created bad name %!q(MISSING); want prefix %!q(MISSING) & suffix %!q(MISSING)

-- FAIL: TestCreateTempPattern

=== RUN  TestCreateTempBadPattern
Exception: T_common:testing.name is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testcreatetempbadpattern_testCreateTempBadPattern [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:47676:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestCreateTempBadPattern

=== RUN  TestMkdirTemp
MkdirTemp(`/_not_exists_`, `foo`) = <invalid reflect.Value>, %!v(MISSING)
- SUBRUN  tempfile_test
MkdirTemp(<invalid reflect.Value>, %!q(MISSING)) created bad name
	%!q(MISSING)
did not match pattern
	%!q(MISSING)
- SUBRUN  tempfile_test*
MkdirTemp(<invalid reflect.Value>, %!q(MISSING)) created bad name
	%!q(MISSING)
did not match pattern
	%!q(MISSING)
- SUBRUN  tempfile_test*xyz
MkdirTemp(<invalid reflect.Value>, %!q(MISSING)) created bad name
	%!q(MISSING)
did not match pattern
	%!q(MISSING)
- SUBRUN  *xyz
MkdirTemp(<invalid reflect.Value>, %!q(MISSING)) created bad name
	%!q(MISSING)
did not match pattern
	%!q(MISSING)

-- FAIL: TestMkdirTemp

=== RUN  TestMkdirTempBadDir
TempDir error = <invalid reflect.Value>; want PathError for path %!q(MISSING) satisfying IsNotExist

-- FAIL: TestMkdirTempBadDir

=== RUN  TestMkdirTempBadPattern
Exception: T_common:testing.name is not yet implemented
Called from module at stdgo__$internal_testing_InternalTest._$internal_os_$test_Os_$test_$testmkdirtempbadpattern_testMkdirTempBadPattern [as f] (/home/runner/work/go2hx/go2hx/golibs/std_os.js:51675:25)
Called from stdgo__$internal_testing_M_$static_$extension.run (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 103330 column 9)
Called from ._$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 50619 column 82)
Called from ._$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js line 92044 column 2)
Called from module at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
Called from module at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
Called from Module._compile (node:internal/modules/cjs/loader line 1734 column 14)
Called from Object..js (node:internal/modules/cjs/loader line 1899 column 10)

-- FAIL: TestMkdirTempBadPattern

golibs/stdgo/_internal/testing/Testing_m_static_extension.hx:91: exitCode: 1 exitCodeReason: 
-- FAIL: TestMkdirTempBadPattern

/home/runner/work/go2hx/go2hx/golibs/std_os.js:65483
	throw haxe_Exception.thrown(":os.exit is not yet implemented");
	^
<ref *1> Error: :os.exit is not yet implemented
    at new haxe_ValueException (/home/runner/work/go2hx/go2hx/golibs/std_os.js:33717:17)
    at haxe_Exception.thrown (/home/runner/work/go2hx/go2hx/golibs/std_os.js:33647:11)
    at stdgo__$internal_os_Os_$exit_exit (/home/runner/work/go2hx/go2hx/golibs/std_os.js:65483:23)
    at _$internal_os_$test_Os_$test_$testmain_testMain (/home/runner/work/go2hx/go2hx/golibs/std_os.js:50619:2)
    at _$internal_osdottest_Osdottest_main (/home/runner/work/go2hx/go2hx/golibs/std_os.js:92044:2)
    at /home/runner/work/go2hx/go2hx/golibs/std_os.js:116060:1
    at Object.<anonymous> (/home/runner/work/go2hx/go2hx/golibs/std_os.js:116061:3)
    at Module._compile (node:internal/modules/cjs/loader:1734:14)
    at Object..js (node:internal/modules/cjs/loader:1899:10)
    at Module.load (node:internal/modules/cjs/loader:1469:32) {
  __previousException: undefined,
  __nativeException: [Circular *1],
  __skipStack: 2,
  value: ':os.exit is not yet implemented'
}

Node.js v23.11.1
